name: Generate and Deploy CSV

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Gerekli Python paketlerini içeren dosya

      - name: Run script and generate CSV
        run: python rrwt.py  # CSV üreten script
        
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Create pages directory
        run: |
          mkdir -p pages
          cp output.csv pages/  # CSV dosyasını pages klasörüne kopyala
          # İsteğe bağlı: CSV'yi görüntülemek için bir HTML sayfası oluştur
          echo '<html><body><h1>CSV Data</h1><pre>' > pages/index.html
          cat output.csv >> pages/index.html
          echo '</pre></body></html>' >> pages/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
